
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.adminLogin,name="adminlogin"),
    path('adminregister',views.adminRegister,name="adminregister"),
    path('adminhome',views.adminHome,name="adminhome"),
    path('logout',views.logout,name="logout"),
    path('getemail',views.getEmail,name="getemail"),
    path('forgotpassword',views.forgotPassword,name="forgotpassword"),
    path('editprofile/<int:id>',views.editProfile,name="editprofile"),
    path('addservices',views.addServices,name="addservices"),
    path('allservices',views.allServices,name="allservices"),
    path('editServices/<int:id>',views.editServices,name="editervices"),
    path('updateServices/<int:id>',views.updateServices,name="updateservices"),
    path('deleteServices/<int:id>',views.deleteServices,name="deleteservices"),
    path('addpossibility',views.addPossibility,name="addpossibilty"),
    path('allpossibility',views.allPossibility,name="allpossibility"),
    path('editpossibility/<int:id>',views.editPossibility,name="editpossibility"),
    path('updatepossibility/<int:id>',views.updatePossibility,name="updatepossibility"),
    path('deletepossibility/<int:id>',views.deletePossibility,name="deletepossibilty"),
    path('addreview',views.addReview,name="addreview"),
    path('allreview',views.allReview,name="allreview"),
    path('editreview/<int:id>',views.editReview,name="editreview"),
    path('updatereview/<int:id>',views.updateReview,name="updatereview"),
    path('deletereview/<int:id>',views.deleteReview,name="deletereview"),
    path('addteam',views.addTeam,name="addteam"),
    path('allteam',views.allTeam,name="allteam"),
    path('editteam/<int:id>',views.editTeam,name="editteam"),
    path('updateteam/<int:id>',views.updateTeam,name="updateteam"),
    path('deleteteam/<int:id>',views.deleteTeam,name="deleteteam"),
    path('addportfolio',views.addPortfolio,name="addportfolio"),
    path('allportfolio',views.allPortfolio,name="allportfolio"),
    path('editportfolio/<int:id>',views.editPortfolio,name="editportfolio"),
    path('updateportfolio/<int:id>',views.updatePortfolio,name="updateportfolio"),
    path('deleteportfolio/<int:id>',views.deletePortfolio,name="deleteportfolio"),
    path('addtechnology',views.addTechnology,name="addtechnology"),
    path('alltechnology',views.allTechnology,name="alltechnology"),
    path('edittechnology/<int:id>',views.editTechnology,name="edittechnology"),
    path('updatetechnology/<int:id>',views.updateTechnology,name="updatetechnology"),
    path('deletetechnology/<int:id>',views.deleteTechnology,name="deletetechnology"),
    path('addcareer',views.addCareer,name="addcareer"),
    path('allcareer',views.allCareer,name="allcareer"),
    path('editcareer/<int:id>',views.editCareer,name="editcareer"),
    path('updatecareer/<int:id>',views.updateCareer,name="updatecareer"),
    path('deletecareer/<int:id>',views.deleteCareer,name="deletecareer"),
    path('addtraining',views.addTraining,name="addtraining"),
    path('alltraining',views.allTraining,name="alltraining"),
    path('edittraining/<int:id>',views.editTraining,name="edittraining"),
    path('updatetraining/<int:id>',views.updateTraining,name="updatetraining"),
    path('deletetraining/<int:id>',views.deleteTraining,name="deletetraining"),
    path('addstudentreview',views.addStudentreview,name="addstudentreview"),
    path('allstudentreview',views.allStudentreview,name="allstudentreview"),
    path('editstudentreview/<int:id>',views.editStudentreview,name="editstudentreview"),
    path('updatestudentreview/<int:id>',views.updateStudentreview,name="updatestudentreview"),
    path('deletestudentreview/<int:id>',views.deleteStudentreview,name="deletestudentreview"),
    path('addcourse',views.addCourse,name="addcourse"),
    path('allcourse',views.allCourse,name="allcourse"),
    path('editcourse/<int:id>',views.editCourse,name="editcourse"),
    path('updatecourse/<int:id>',views.updateCourse,name="updatecourse"),
    path('deletecourse/<int:id>',views.deleteCourse,name="deletecourse"),
    path('addblog',views.addBlog,name="addblog"),
    path('allblog',views.allBlog,name="allblog"),
    path('editblog/<int:id>',views.editBlog,name="editblog"),
    path('updateblog/<int:id>',views.updateBlog,name="updateblog"),
    path('deleteblog/<int:id>',views.deleteBlog,name="deleteblog"),
    path('adminwebcontact',views.webcontact,name="adminwebcontact"),
    path('admindeletewebcontact/<int:id>',views.deletewebcontact,name="deletewebcontact"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
